[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["zzz"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
langgraph = "^0.2.70"
ipython = "^8.32.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
