services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ~/.ssh:/opt/motiong/.ssh
      - ../.devcontainer/zshrc:/opt/motiong/.zshrc
      - ..:/opt/motiong/code
    command: ["tail -f /dev/null"]
    